### ISSUE TITLE
open_library_api - prepare codebase to accomodate open_library_api

### ISSUE THREAD

**Issue by bllendev** [bllendev/kalibre#153]
## Description
- have to prepare the codebase a bit to maintain distinctions and useability

## TODO
- [x] create new books/api/ directory
- [x] create api_openlibrary.py
- [x] change existing imports to reflect new directory change
- [x] add __init__.py module to new directory

## Snips
<img width="572" alt="image" src="https://github.com/bllendev/kalibre/assets/113651082/477d08d1-2a90-4a1a-b4c6-9b1950b34d2f">
