### ISSUE TITLE
open_library_api - OpenLibraryAPI class and test

### ISSUE THREAD

**Issue by bllendev** [bllendev/kalibre#154]
## description
- beginning init and build of api class to handle OpenLibraryAPI Integration

## todo
- [ ] rename existing get_unique_book_list methods
- [ ] create new class with placeholder methods
- [ ] create new test class with placeholder methods
- [ ] add docs to class of usage and expected outputs

## snips
<img width="544" alt="image" src="https://github.com/bllendev/kalibre/assets/113651082/1c1d9fa1-efcd-4d4a-ba9d-0eef241f40ed">
