### ISSUE TITLE
migrate - db AI model

### ISSUE THREAD

**Issue by bllendev** [bllendev/kalibre#42]
- [ ] create a OpenAIQuery model
- [ ] consider how to handle strings of messages

#### fields
- [ ] messages
- [ ] max_tokens
- [ ] temperature

#### todo
- [ ] add method to get query
- [ ] ...... test
- [ ] add method to get response
- [ ] ....... test

**Comment by bllendev** [comment]
this issue was disseminated to other issues in the milestone
